project_id = "fnhoztuwzlzarkryhfen"

[functions.convert-file]
verify_jwt = false

[functions.pdf-edit]
verify_jwt = false

[functions.generate-resume]
verify_jwt = false

[functions.social-downloader]
verify_jwt = false

[functions.ai-tools]
verify_jwt = false
